/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddProgram: typeof import('./components/workplace/AddProgram.vue')['default']
    AddProgramCard: typeof import('./components/workplace/AddProgramCard.vue')['default']
    Banner: typeof import('./components/workplace/Banner.vue')['default']
    ChannelCard: typeof import('./components/global/ChannelCard.vue')['default']
    ChannelInfoCard: typeof import('./components/workplace/ChannelInfoCard.vue')['default']
    ChannelInfoCardGroup: typeof import('./components/workplace/ChannelInfoCardGroup.vue')['default']
    ChannelListCard: typeof import('./components/global/ChannelListCard.vue')['default']
    copy: typeof import('./components/workplace/ProgramInfoCard copy.vue')['default']
    DataPanel: typeof import('./components/workplace/data-panel.vue')['default']
    Footer: typeof import('./components/global/Footer.vue')['default']
    IndexCarousel: typeof import('./components/index/IndexCarousel.vue')['default']
    IndexContentSwitch: typeof import('./components/index/IndexContentSwitch.vue')['default']
    IndexSwitch: typeof import('./components/global/IndexSwitch.vue')['default']
    ListProgramByNameGroup: typeof import('./components/workplace/ListProgramByNameGroup.vue')['default']
    LoginCarousel: typeof import('./components/login/LoginCarousel.vue')['default']
    LoginForm: typeof import('./components/login/LoginForm.vue')['default']
    Menu: typeof import('./components/workplace/Menu.vue')['default']
    MyScheduleInfoCard: typeof import('./components/workplace/MyScheduleInfoCard.vue')['default']
    MySubscribeTimeline: typeof import('./components/workplace/MySubscribeTimeline.vue')['default']
    Navbar: typeof import('./components/global/Navbar.vue')['default']
    ProgramCard: typeof import('./components/global/ProgramCard.vue')['default']
    ProgramInfoCard: typeof import('./components/workplace/ProgramInfoCard.vue')['default']
    ProgramInfoCardGroup: typeof import('./components/workplace/ProgramInfoCardGroup.vue')['default']
    ProgramListCard: typeof import('./components/global/ProgramListCard.vue')['default']
    ProgramNoDeleteInfoCard: typeof import('./components/workplace/ProgramNoDeleteInfoCard.vue')['default']
    ProgramTimeline: typeof import('./components/global/ProgramTimeline.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleInfoCard: typeof import('./components/workplace/ScheduleInfoCard.vue')['default']
    ScheduleInfoCardNoFunc: typeof import('./components/workplace/ScheduleInfoCardNoFunc.vue')['default']
    SProgramInfoCard: typeof import('./components/workplace/SProgramInfoCard.vue')['default']
    SubscribeTimeline: typeof import('./components/workplace/SubscribeTimeline.vue')['default']
    SubscribeTimelineByCategory: typeof import('./components/workplace/SubscribeTimelineByCategory.vue')['default']
    SubscribeTimelineByChannel: typeof import('./components/workplace/SubscribeTimelineByChannel.vue')['default']
    SubscribeTimelineByName: typeof import('./components/workplace/SubscribeTimelineByName.vue')['default']
    SubscribeTimelineByPeriod: typeof import('./components/workplace/SubscribeTimelineByPeriod.vue')['default']
    SysInfo: typeof import('./components/workplace/SysInfo.vue')['default']
    Timel: typeof import('./components/global/Timel.vue')['default']
    TimeL: typeof import('./components/global/TimeL.vue')['default']
    WorkplaceMenu: typeof import('./components/workplace/WorkplaceMenu.vue')['default']
  }
}
