/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./components/global/Footer.vue')['default']
    IndexCarousel: typeof import('./components/index/IndexCarousel.vue')['default']
    IndexContentSwitch: typeof import('./components/index/IndexContentSwitch.vue')['default']
    IndexSwitch: typeof import('./components/global/IndexSwitch.vue')['default']
    LoginCarousel: typeof import('./components/login/LoginCarousel.vue')['default']
    LoginForm: typeof import('./components/login/LoginForm.vue')['default']
    Navbar: typeof import('./components/global/Navbar.vue')['default']
    ProgramCard: typeof import('./components/global/ProgramCard.vue')['default']
    ProgramListCard: typeof import('./components/global/ProgramListCard.vue')['default']
    ProgramTimeline: typeof import('./components/global/ProgramTimeline.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Timel: typeof import('./components/global/Timel.vue')['default']
    TimeL: typeof import('./components/global/TimeL.vue')['default']
  }
}
