/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./components/global/Footer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginBanner: typeof import('./components/login/LoginBanner.vue')['default']
    LoginCarousel: typeof import('./components/login/LoginCarousel.vue')['default']
    LoginForm: typeof import('./components/login/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
