name: Frontend Docker Build
on:
  push:
    branches:
      - main
    paths:
      - frontend/**

jobs:
  docker_publish:
    runs-on: "ubuntu-20.04"

    steps:
      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: create image from repository
        run: docker build -t ghcr.io/${{ github.actor }}/tivemachine-frontend -f frontend/Dockerfile frontend
      - name: push image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.actor }}/tivemachine-frontend:latest